export default  [
  {
    image: "avengers.jpg",
    rate: "8.4",
    name: "Avengers-Endgame",
    genre: "Action/Sci-fi",
    time: "3h 02m",
    year: "2019",
    link: "https://www.imdb.com/title/tt4154796/",
  },

  {
    image: "infinity-war.jpg",
    rate: "8.4",
    name: "Avengers-Infinity War",
    genre: "Action/Adventure",
    time: " 2h 29m",
    year: "2018",
    link: "https://www.imdb.com/title/tt4154756/",
  },

  {
    image: "spiderman-no way home.avif",
    rate: "8.2",
    name: "Spiderman-No way home",
    genre: "Sci-fi/superhero",
    time: " 2h 28m",
    year: "2021",
    link: "https://www.imdb.com/title/tt10872600/",
  },

  {
    image: "thor-ragnarok.jpg",
    rate: "8.2",
    name: "Thor- Ragnarok",
    genre: "Action/Adventure",
    time: " 2h 10m",
    year: "2017",
    link: "https://www.imdb.com/title/tt3501632/",
  }
  ,
  {
    image: "civil-war.jpg",
    rate: "7.8",
    name: "Captain America: Civil War",
    genre: "Action/Adventure",
    time: " 2h 27m",
    year: "2016",
    link: "https://www.imdb.com/title/tt3498820/",
  },

  {
    image: "gotg.jpg",
    rate: "8.0",
    name: "Guardians of the Galaxy 3",
    genre: "Action/Sci-Fi",
    time: " 2h 29m",
    year: "2023",
    link: "https://www.imdb.com/title/tt6791350/",
  },
{
    image: "iron-man.jpg",
    rate: "7.9",
    name: "Iron Man",
    genre: "Action/Sci-Fi",
    time: " 2h 06m",
    year: "2008",
    link: "https://www.imdb.com/title/tt0371746/",
  },
{
    image: "captain-america.jpg",
    rate: "7.8",
    name: "Captain America-The Winter Soldier",
    genre: "Action/Adventure",
    time: " 2h 16m",
    year: "2014",
    link: "https://www.imdb.com/title/tt1843866/",
  },
{
    image: "thor-4.jpg",
    rate: "6.2",
    name: "Thor: Love and Thunder",
    genre: "Action/Sci-Fi",
    time: " 1h 59m",
    year: "2022",
    link: "https://www.imdb.com/title/tt10648342/",
  },
{
    image: "dr-strange.jpg",
    rate: "6.9",
    name: "Doctor Strange-Multiverse Of Madness",
    genre: "Action/Adventure",
    time: " 2h 06m",
    year: "2022",
    link: "https://www.imdb.com/title/tt9419884/",
  },


  {
    image: "dr-strange.jpg",
    rate: "6.9",
    name: "Doctor Strange-Multiverse Of Madness",
    genre: "Action/Adventure",
    time: " 2h 06m",
    year: "2022",
    link: "https://www.imdb.com/title/tt9419884/",
  },
  {
    image: "dr-strange.jpg",
    rate: "6.9",
    name: "Doctor Strange-Multiverse Of Madness",
    genre: "Action/Adventure",
    time: " 2h 06m",
    year: "2022",
    link: "https://www.imdb.com/title/tt9419884/",
  },
  {
    image: "dr-strange.jpg",
    rate: "6.9",
    name: "Doctor Strange-Multiverse Of Madness",
    genre: "Action/Adventure",
    time: " 2h 06m",
    year: "2022",
    link: "https://www.imdb.com/title/tt9419884/",
  },
  {
    image: "dr-strange.jpg",
    rate: "6.9",
    name: "Doctor Strange-Multiverse Of Madness",
    genre: "Action/Adventure",
    time: " 2h 06m",
    year: "2022",
    link: "https://www.imdb.com/title/tt9419884/",
  },
  {
    image: "dr-strange.jpg",
    rate: "6.9",
    name: "Doctor Strange-Multiverse Of Madness",
    genre: "Action/Adventure",
    time: " 2h 06m",
    year: "2022",
    link: "https://www.imdb.com/title/tt9419884/",
  },
  {
    image: "dr-strange.jpg",
    rate: "6.9",
    name: "Doctor Strange-Multiverse Of Madness",
    genre: "Action/Adventure",
    time: " 2h 06m",
    year: "2022",
    link: "https://www.imdb.com/title/tt9419884/",
  },

  {
    image: "dr-strange.jpg",
    rate: "6.9",
    name: "Doctor Strange-Multiverse Of Madness",
    genre: "Action/Adventure",
    time: " 2h 06m",
    year: "2022",
    link: "https://www.imdb.com/title/tt9419884/",
  }, {
    image: "dr-strange.jpg",
    rate: "6.9",
    name: "Doctor Strange-Multiverse Of Madness",
    genre: "Action/Adventure",
    time: " 2h 06m",
    year: "2022",
    link: "https://www.imdb.com/title/tt9419884/",
  }, {
    image: "dr-strange.jpg",
    rate: "6.9",
    name: "Doctor Strange-Multiverse Of Madness",
    genre: "Action/Adventure",
    time: " 2h 06m",
    year: "2022",
    link: "https://www.imdb.com/title/tt9419884/",
  }, {
    image: "dr-strange.jpg",
    rate: "6.9",
    name: "Doctor Strange-Multiverse Of Madness",
    genre: "Action/Adventure",
    time: " 2h 06m",
    year: "2022",
    link: "https://www.imdb.com/title/tt9419884/",
  }, {
    image: "dr-strange.jpg",
    rate: "6.9",
    name: "Doctor Strange-Multiverse Of Madness",
    genre: "Action/Adventure",
    time: " 2h 06m",
    year: "2022",
    link: "https://www.imdb.com/title/tt9419884/",
  }, {
    image: "dr-strange.jpg",
    rate: "6.9",
    name: "Doctor Strange-Multiverse Of Madness",
    genre: "Action/Adventure",
    time: " 2h 06m",
    year: "2022",
    link: "https://www.imdb.com/title/tt9419884/",
  }, {
    image: "dr-strange.jpg",
    rate: "6.9",
    name: "Doctor Strange-Multiverse Of Madness",
    genre: "Action/Adventure",
    time: " 2h 06m",
    year: "2022",
    link: "https://www.imdb.com/title/tt9419884/",
  },
  

];
